name: data-types
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  exposed-modules: DataTypes
  source-dirs: src
  ghc-options: -Wall

tests:
  data-types-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - data-types
      - hspec
